import { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Wallet, Download, Plus, Printer } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { getDataStore, saveDataStore, Payrun } from '@/lib/dataStore';
import { format } from 'date-fns';
import { useToast } from '@/hooks/use-toast';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';

export default function Payroll() {
  const { currentUser } = useAuth();
  const { toast } = useToast();
  const [isGenerateDialogOpen, setIsGenerateDialogOpen] = useState(false);
  const [selectedPayslip, setSelectedPayslip] = useState<any>(null);
  const [isPayslipDialogOpen, setIsPayslipDialogOpen] = useState(false);
  const [selectedMonth, setSelectedMonth] = useState(format(new Date(), 'yyyy-MM'));

  const data = getDataStore();

  const canGenerate = currentUser?.role === 'admin' || currentUser?.role === 'payroll';

  const handleGeneratePayrun = () => {
    if (!currentUser) return;

    const settings = data.settings;
    const items = data.users.map(user => {
      const gross = user.salary.basic + user.salary.hra + user.salary.otherEarnings;
      const pf = (user.salary.basic * settings.pfPercent) / 100;
      const deductions = pf + settings.professionalTax;
      const net = gross - deductions;

      return {
        userId: user.id,
        gross,
        deductions,
        net
      };
    });

    const totalPayroll = items.reduce((sum, item) => sum + item.net, 0);

    const newPayrun: Payrun = {
      id: `p${Date.now()}`,
      month: selectedMonth,
      generatedBy: currentUser.id,
      totalPayroll,
      items
    };

    data.payruns.push(newPayrun);
    saveDataStore(data);

    toast({
      title: 'Payrun Generated',
      description: `Payroll for ${format(new Date(selectedMonth), 'MMMM yyyy')} has been generated`
    });

    setIsGenerateDialogOpen(false);
  };

  const viewPayslip = (payrun: Payrun, userId: string) => {
    const user = data.users.find(u => u.id === userId);
    const item = payrun.items.find(i => i.userId === userId);
    
    if (user && item) {
      setSelectedPayslip({
        user,
        payrun,
        item,
        settings: data.settings
      });
      setIsPayslipDialogOpen(true);
    }
  };

  const printPayslip = () => {
    window.print();
  };

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold mb-2">Payroll Management</h1>
          <p className="text-muted-foreground">
            Generate payruns and manage payslips
          </p>
        </div>
        
        {canGenerate && (
          <Dialog open={isGenerateDialogOpen} onOpenChange={setIsGenerateDialogOpen}>
            <DialogTrigger asChild>
              <Button data-testid="button-generate-payrun">
                <Plus className="w-4 h-4 mr-2" />
                Generate Payrun
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Generate Payrun</DialogTitle>
                <DialogDescription>
                  Create a new payrun for the selected month
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
                <div className="space-y-2">
                  <Label htmlFor="month">Select Month</Label>
                  <Input
                    id="month"
                    type="month"
                    value={selectedMonth}
                    onChange={(e) => setSelectedMonth(e.target.value)}
                    data-testid="input-payrun-month"
                  />
                </div>
              </div>
              <DialogFooter>
                <Button onClick={handleGeneratePayrun} data-testid="button-submit-payrun">
                  Generate
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        )}
      </div>

      <Card className="p-6">
        <h2 className="text-xl font-semibold mb-4">Payruns</h2>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Month</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Total Payroll</TableHead>
              <TableHead>Employees</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {data.payruns.length === 0 ? (
              <TableRow>
                <TableCell colSpan={5} className="text-center py-8 text-muted-foreground">
                  No payruns generated yet
                </TableCell>
              </TableRow>
            ) : (
              data.payruns.slice().reverse().map(payrun => {
                const generatedBy = data.users.find(u => u.id === payrun.generatedBy);
                return (
                  <TableRow key={payrun.id}>
                    <TableCell>{format(new Date(payrun.month), 'MMMM yyyy')}</TableCell>
                    <TableCell>{generatedBy?.name || 'Unknown'}</TableCell>
                    <TableCell className="font-semibold">₹{payrun.totalPayroll.toLocaleString()}</TableCell>
                    <TableCell>{payrun.items.length}</TableCell>
                    <TableCell>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => currentUser && viewPayslip(payrun, currentUser.id)}
                        data-testid={`button-view-payslip-${payrun.id}`}
                      >
                        <Download className="w-4 h-4 mr-2" />
                        View Payslip
                      </Button>
                    </TableCell>
                  </TableRow>
                );
              })
            )}
          </TableBody>
        </Table>
      </Card>

      <Dialog open={isPayslipDialogOpen} onOpenChange={setIsPayslipDialogOpen}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle>Payslip</DialogTitle>
          </DialogHeader>
          {selectedPayslip && (
            <div className="space-y-6 font-mono">
              <div className="text-center border-b pb-4">
                <h2 className="text-2xl font-bold">WorkZen HRMS</h2>
                <p className="text-sm text-muted-foreground">Payslip for {format(new Date(selectedPayslip.payrun.month), 'MMMM yyyy')}</p>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm text-muted-foreground">Employee Name</p>
                  <p className="font-semibold">{selectedPayslip.user.name}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Employee ID</p>
                  <p className="font-semibold">{selectedPayslip.user.id}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Department</p>
                  <p className="font-semibold">{selectedPayslip.user.department}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Designation</p>
                  <p className="font-semibold capitalize">{selectedPayslip.user.role}</p>
                </div>
              </div>

              <div className="border-t pt-4">
                <h3 className="font-semibold mb-4">Earnings</h3>
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <span>Basic Salary</span>
                    <span>₹{selectedPayslip.user.salary.basic.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between">
                    <span>HRA</span>
                    <span>₹{selectedPayslip.user.salary.hra.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Other Earnings</span>
                    <span>₹{selectedPayslip.user.salary.otherEarnings.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between font-semibold border-t pt-2">
                    <span>Gross Salary</span>
                    <span>₹{selectedPayslip.item.gross.toLocaleString()}</span>
                  </div>
                </div>
              </div>

              <div className="border-t pt-4">
                <h3 className="font-semibold mb-4">Deductions</h3>
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <span>PF ({selectedPayslip.settings.pfPercent}%)</span>
                    <span>₹{((selectedPayslip.user.salary.basic * selectedPayslip.settings.pfPercent) / 100).toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Professional Tax</span>
                    <span>₹{selectedPayslip.settings.professionalTax.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between font-semibold border-t pt-2">
                    <span>Total Deductions</span>
                    <span>₹{selectedPayslip.item.deductions.toLocaleString()}</span>
                  </div>
                </div>
              </div>

              <div className="border-t pt-4">
                <div className="flex justify-between text-xl font-bold">
                  <span>Net Salary</span>
                  <span>₹{selectedPayslip.item.net.toLocaleString()}</span>
                </div>
              </div>

              <div className="flex gap-2">
                <Button onClick={printPayslip} className="flex-1" data-testid="button-print-payslip">
                  <Printer className="w-4 h-4 mr-2" />
                  Print
                </Button>
                <Button
                  variant="outline"
                  onClick={() => toast({ title: 'Download started', description: 'Payslip will be downloaded as PDF' })}
                  className="flex-1"
                  data-testid="button-download-payslip"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download PDF
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
